/** @type {import('tailwindcss').Config} */

// Shared shape tokens: sharp, terminal-like corners and no button bounce
const shape = {
    '--rounded-box': '0.375rem',
    '--rounded-btn': '0.25rem',
    '--rounded-badge': '0.25rem',
    '--animation-btn': '0',
    '--animation-input': '0',
    '--btn-focus-scale': '1',
    '--border-btn': '1px',
    '--tab-radius': '0.25rem',
};

module.exports = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Hack', 'ui-monospace', 'monospace'],
                mono: ['Hack', 'ui-monospace', 'monospace'],
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic':
                    'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
            },
        },
    },
    plugins: [require('daisyui'), require('@tailwindcss/typography')],
    daisyui: {
        // Palettes follow each colorscheme's terminal definition: base-100 is the
        // terminal background, base-content its foreground, the rest its ANSI colors
        themes: [
            {
                rosepine_light: {
                    ...shape,
                    'primary': '#286983',
                    'secondary': '#907aa9',
                    'accent': '#d7827e',
                    'neutral': '#f2e9e1',
                    'base-100': '#faf4ed',
                    'base-200': '#f2e9e1',
                    'base-300': '#dfdad9',
                    'base-content': '#575279',
                    'info': '#56949f',
                    'success': '#286983',
                    'warning': '#ea9d34',
                    'error': '#b4637a',
                },
            },
            {
                rosepine_dark: {
                    ...shape,
                    'primary': '#9ccfd8',
                    'secondary': '#c4a7e7',
                    'accent': '#ebbcba',
                    'neutral': '#26233a',
                    'base-100': '#191724',
                    'base-200': '#1f1d2e',
                    'base-300': '#403d52',
                    'base-content': '#e0def4',
                    'info': '#9ccfd8',
                    'success': '#31748f',
                    'warning': '#f6c177',
                    'error': '#eb6f92',
                },
            },
            {
                tokyonight_light: {
                    ...shape,
                    'primary': '#2e7de9',
                    'secondary': '#9854f1',
                    'accent': '#b15c00',
                    'neutral': '#c4c8da',
                    'base-100': '#e1e2e7',
                    'base-200': '#d0d5e3',
                    'base-300': '#c4c8da',
                    'base-content': '#3760bf',
                    'info': '#007197',
                    'success': '#587539',
                    'warning': '#8c6c3e',
                    'error': '#f52a65',
                },
            },
            {
                tokyonight_dark: {
                    ...shape,
                    'primary': '#7aa2f7',
                    'secondary': '#bb9af7',
                    'accent': '#ff9e64',
                    'neutral': '#292e42',
                    'base-100': '#1a1b26',
                    'base-200': '#1f2335',
                    'base-300': '#292e42',
                    'base-content': '#c0caf5',
                    'info': '#7dcfff',
                    'success': '#9ece6a',
                    'warning': '#e0af68',
                    'error': '#f7768e',
                },
            },
            {
                gruvbox_light: {
                    ...shape,
                    'primary': '#076678',
                    'secondary': '#8f3f71',
                    'accent': '#af3a03',
                    'neutral': '#d5c4a1',
                    'base-100': '#fbf1c7',
                    'base-200': '#f2e5bc',
                    'base-300': '#ebdbb2',
                    'base-content': '#3c3836',
                    'info': '#427b58',
                    'success': '#79740e',
                    'warning': '#b57614',
                    'error': '#9d0006',
                },
            },
            {
                gruvbox_dark: {
                    ...shape,
                    'primary': '#83a598',
                    'secondary': '#d3869b',
                    'accent': '#fe8019',
                    'neutral': '#504945',
                    'base-100': '#282828',
                    'base-200': '#32302f',
                    'base-300': '#504945',
                    'base-content': '#ebdbb2',
                    'info': '#8ec07c',
                    'success': '#b8bb26',
                    'warning': '#fabd2f',
                    'error': '#fb4934',
                },
            },
            {
                nord_light: {
                    ...shape,
                    'primary': '#5e81ac',
                    'secondary': '#b48ead',
                    'accent': '#d08770',
                    'neutral': '#d8dee9',
                    'base-100': '#eceff4',
                    'base-200': '#e5e9f0',
                    'base-300': '#d8dee9',
                    'base-content': '#2e3440',
                    'info': '#5e81ac',
                    'success': '#6b8f4e',
                    'warning': '#b58a2e',
                    'error': '#bf616a',
                },
            },
            {
                nord_dark: {
                    ...shape,
                    'primary': '#88c0d0',
                    'secondary': '#b48ead',
                    'accent': '#d08770',
                    'neutral': '#4c566a',
                    'base-100': '#2e3440',
                    'base-200': '#3b4252',
                    'base-300': '#4c566a',
                    'base-content': '#d8dee9',
                    'info': '#81a1c1',
                    'success': '#a3be8c',
                    'warning': '#ebcb8b',
                    'error': '#bf616a',
                },
            },
        ],
    },
};
